mod/mod/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from modapp.api_views import RegionViewSet, SkillsViewSet

router = routers.DefaultRouter()
router.register(r'regions', RegionViewSet)
router.register(r'skills', SkillsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modapp.urls', namespace='mod')),
    path('user/', include('userapp.urls', namespace='user')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    # path('skills/', include(router.urls))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

mod/modapp/urls.py
from modapp import views
from django.urls import path

app_name = 'modapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('contact/', views.contact_view, name='contact'),
    path('create/', views.create_post, name='create'),
    path('post/<int:id>/', views.post, name='post'),
    path('region-list', views.RegionListView.as_view(), name='region_list'),
    path('full-detail/<int:pk>/', views.FullDetailView.as_view(), name='full_detail'),
    path('region-create/', views.RegionCreateView.as_view(), name='region_create'),
    path('region-update/<int:pk>/', views.RegionUpdateView.as_view(), name='region_update'),
    path('region-delete/<int:pk>/', views.RegionDeleteView.as_view(), name='region_delete')
]

mod/modapp/models.py
from django.db import models
from userapp.models import BlogUser



# Create your models here.
# Создаем модель нашей базы данных
class Region(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Skills(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    name = models.CharField(max_length=32, unique=True)
    image = models.ImageField(upload_to='posts', null=True, blank=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)



    def has_image(self):
        return bool(self.image)

    def some_method(self):
        return 'hello from method'

    def __str__(self):
        return f'{self.name}'


class NumberOffer(models.Model):
    name = models.CharField(max_length=32, unique=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class FullOffer(models.Model):
    numberOffer = models.ForeignKey(NumberOffer, on_delete=models.CASCADE)
    VACANCY = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    REGION = models.ForeignKey(Region, on_delete=models.CASCADE)
    SKILLS = models.ForeignKey(Skills, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s %s %s' % (self.numberOffer, self.VACANCY, self.REGION, self.SKILLS)

mod/modapp/forms.py
from django import forms

from modapp.models import Vacancy


class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class PostForm(forms.ModelForm):
    name = forms.CharField(label='Название')
    class Meta:
        model = Vacancy
        #fields = '__all__'
        exclude = ('user',)

mod/modapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, HttpResponseRedirect
from .models import FullOffer, Region
from .forms import ContactForm, PostForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def main_view(request):
    fulls = FullOffer.objects.all()
    paginator = Paginator(fulls, 2)
    page = request.GET.get('page')
    try:
        fulls = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        fulls = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        fulls = paginator.page(paginator.num_pages)

    title = 'привет'

    return render(request, 'modapp/index.html', context={'fulls': fulls, 'title': title})




def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Получить данные из форы
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']

            send_mail(
                'Contact message',
                f'Ваш сообщение {message} принято',
                'from@example.com',
                [email],
                fail_silently=True,
            )

            return HttpResponseRedirect(reverse('mod:index'))
        else:
            return render(request, 'modapp/contact.html', context={'form': form})
    else:
        form = ContactForm()
    return render(request, 'modapp/contact.html', context={'form': form})


@user_passes_test(lambda u: u.is_superuser)
def post(request, id):
    fulls = FullOffer.objects.get(id=id)
    return render(request, 'modapp/post.html', context={'fulls': fulls})


@login_required
def create_post(request):
    if request.method == 'GET':
        form = PostForm()
        return render(request, 'modapp/create.html', context={'form': form})
    else:
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('mod:index'))
        else:
            return render(request, 'modapp/create.html', context={'form': form})


class RegionListView(ListView):
    model = Region
    template_name = 'region_list.html'
    context_object_name = 'regions'
    paginate_by = 2

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'Регионы'
        return context


class FullDetailView(DetailView):
    model = FullOffer
    template_name = 'modapp/full_detail.html'

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :return:
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'Регионы'
        return context


class RegionCreateView(LoginRequiredMixin, CreateView):
    model = Region
    fields = '__all__'
    success_url = reverse_lazy('mod:region_list')
    template_name = 'modapp/region_create.html'

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        # self.request.user - текущий пользователь
        form.instance.user = self.request.user
        return super().form_valid(form)


class RegionUpdateView(UpdateView):
    model = Region
    fields = '__all__'
    success_url = reverse_lazy('mod:region_list')
    template_name = 'modapp/region_create.html'


class RegionDeleteView(DeleteView):
    template_name = 'modapp/region_delete_confirm.html'
    model = Region
    success_url = reverse_lazy('mod:region_list')

mod/modapp/templates/modapp/contact.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as
            possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form method="post" id="contactForm">
            {% csrf_token %}
            {{ form.as_table }}
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
             {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
        </form>
    </div>
</div>
{% endblock %}

mod/modapp/templates/modapp/create.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_table }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
             {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </div>
            {% endfor %}
        </form>
    </div>
</div>
{% endblock %}

mod/modapp/templates/modapp/full_detail.html
{% extends "base.html" %}

{% block title %}
  {{object.name}}
{% endblock %}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>


</div>
{% endblock %}

mod/modapp/templates/modapp/index.html
{% extends "base.html" %}
{% load str_extensions %}

{% block title %}
   Главная страница
{% endblock %}

{% block content %}


    <div class="row">

      <div class="col-lg-8 col-md-10 mx-auto">

          {% with cash_fulls=fulls %}
                {% for item in cash_fulls %}
                <div class="post-preview">
                  <a href="{% url 'mod:post' id=item.id %}">
                    <h2 class="post-title">
                      {{ item.VACANCY }}
                    </h2>
                    <h3 class="post-subtitle">
                      {{ item.REGION }}
                    </h3>
                  </a>
                  <p class="post-meta">Posted by
                    <a href="#">Start Bootstrap</a>
                    on September 24, 2019
                   {% if item.has_image %}
                        Есть картинка
                        {% else%}
                        Нет картинки
                    {% endif %}
                    {{item.has_image}}
                      {{item.some_method}}
                  </p>
                </div>
                <hr>
                {% endfor %}
          {% endwith %}
        <!-- Pager -->
        <div class="clearfix">
          <div class="pagination">

            <span class="step-links">
                {% if fulls.has_previous %}
                    <a href="?page={{ fulls.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ fulls.number }} of {{ fulls.paginator.num_pages }}.
                </span>

                {% if fulls.has_next %}
{#               <a href="?page={{ fulls.next_page_number }}">next</a> #}


                    <a class="btn btn-primary float-right"
                       href="?page={{ fulls.next_page_number }}">Older vacancy &rarr;</a>

                {% endif %}


            </span>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

mod/modapp/templates/modapp/post.html
{% extends "base.html" %}

{% block title %}
  {{fulls.VACANCY}}
{% endblock %}

{% block content %}

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <img src="{{fulls.VACANCY.image.url}}" width="300">
            {{fulls.REGION}}
        </div>
      </div>
{% endblock %}

mod/modapp/templates/modapp/region_create.html
{% extends "base.html" %}

{% block title %}
Новый регион
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

mod/modapp/templates/modapp/region_delete_confirm.html
{% extends "base.html" %}

{% block title %}
  {{object.name}}
{% endblock %}

{% block content %}

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{object.name}}
        </div>
          Вы уверены?
          <form method="post" class="btn btn-danger">
              {% csrf_token %}
              <button type="submit">ДА</button>
          </form>
      </div>
{% endblock %}

mod/modapp/templates/modapp/region_list.html
{% extends "base.html" %}

{% block title %}
   Список регионов
{% endblock %}

{% block content %}
<h1>{{name}}</h1>
   <ul>
       {% for item in regions %}
       <li>
           <a href="{% url 'mod:full_detail' pk=item.pk %}">
               {{item.name}}
           </a>
           /
           <a href="{% url 'mod:region_update' pk=item.pk %}">Изменить регион</a>
           /
           <a href="{% url 'mod:region_delete' pk=item.pk %}">Удалить регион</a>
       </li>
       {% endfor %}
       <a href="{% url 'mod:region_create'%}">Ввести новый регион</a>
   </ul>
{% endblock %}