mod/mod/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from modapp.api_views import RegionViewSet, SkillsViewSet

router = routers.DefaultRouter()
router.register(r'regions', RegionViewSet)
router.register(r'skills', SkillsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modapp.urls', namespace='mod')),
    path('user/', include('userapp.urls', namespace='user')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    # path('skills/', include(router.urls))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

mod/modapp/urls.py
from modapp import views
from django.urls import path

app_name = 'modapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('contact/', views.contact_view, name='contact'),
    path('create/', views.create_post, name='create'),
    path('post/<int:id>/', views.post, name='post'),
    path('region-list', views.RegionListView.as_view(), name='region_list'),
    path('full-detail/<int:pk>/', views.FullDetailView.as_view(), name='full_detail'),
    path('region-create/', views.RegionCreateView.as_view(), name='region_create'),
    path('region-update/<int:pk>/', views.RegionUpdateView.as_view(), name='region_update'),
    path('region-delete/<int:pk>/', views.RegionDeleteView.as_view(), name='region_delete')
]

mod/userapp/urls.py
from userapp import views
from django.urls import path
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
]

mod/templates/base.html
{% load static %}
{% load str_extensions %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'mod:index' %}>Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'mod:contact' %}>контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'mod:create' %}>добавить данные</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'mod:region_list' %}>список регионов</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    Привет, <a href="{% url 'users:profile' pk=user.pk %}">{{user.username}}</a>
                    <a class="nav-link" href={% url 'user:logout' %}>выход</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href={% url 'user:register' %}>Регистрация</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href={% url 'user:login' %}>вход</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>{{title|capitalize}}</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    {% block content %}{% endblock %}
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>